[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "QuickServe"
version = "0.0.1"
requires-python = ">=3.14"
dependencies = ["tomli-w", "pydantic", "peewee", "flask", "flask-login", "websockets", "requests"]

[tool.setuptools.packages.find]
where = ["src"]
